#! /usr/bin/env bash

function run {
        notangle -t8 -RMakefile "$1" > Makefile
        if [ ${PWD##*/} != "lir-tutorial" ]
        then
                if grep --line-regexp --quiet "# Bibliography" "$1"
                then
                        cp --update ../../anagrams.bib ./anagrams.bib
                fi
                if grep --line-regexp --quiet "<<:source en-dict>>=" "$1"
                then
                        cp --update ../../en-dict ./en-dict
                fi
        fi
        make
}

LAST=$(ls -1 -v *-p.lir | tail -n 1 | sed "s/^\(.\+\)-p\.lir$/\1/")
typeset -i n=$LAST

for x in $(seq 1 "$n") 
do
        swipl -g 'main,halt' -t 'halt(1)' from-parts.pl "$x" \
                > "../docs/$x/anagrams.lir"
        if noroots ../docs/$x/anagrams.lir | grep -q Makefile
        then
                (cd ../docs/$x ; run anagrams.lir)
        else
                (cd ../docs/$x ; lir anagrams.lir)
        fi
done

swipl -g 'main,halt' -t 'halt(1)' from-parts.pl $n \
        > "../anagrams.lir"
(cd .. ; run anagrams.lir ; cp anagrams.html docs)
